apiVersion: v1
kind: Service
metadata:
  labels:
    app: placeholdertobereplacedbyvocusapplicationnameincicdpipeline
  name: placeholdertobereplacedbyvocusapplicationnameincicdpipelineservice
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 5000
  selector:
    app: placeholdertobereplacedbyvocusapplicationnameincicdpipeline
  type: LoadBalancer
